### PR TITLE
chore(lint): use more standard TSLint config

### PR DESCRIPTION
**Pull request by benjie**
- don't use namespace
- don't use interfaces starting with `I`
- remove a number of formatting rules now served by prettier

### CODE REVIEW

**Comment by benjie** [comment]
@cdaringe I'm trying to move from our entirely custom tslint config to use the recommended config as much as possible. This PR is a step towards that; but it simplifies some of the code you did in #794. Are you hesitant about any of these changes (specifically, does using the namespace give any advantages? Importing directly seems a lot more convenient and simply requiring from the interfaces file seems to be a namespace anyway.

**Comment by sjmcdowall** [comment]
I am sort of wondering if you want to try to use 
    "tslint-consistent-codestyle"
in the tslint.json ?  Before the prettier so it doesn't interfere.. that may even have more standard coding stuff "we" want to do (and I use it in all my projects) .. <shrug> 

As for namespace stuff -- since TS 2.6 or so that's pretty deprecated mostly and now is seen as not best practices using them unless really needed ... So I like the direction this is going ... <shrug>

**Comment by benjie** [comment]
> One question -- why the "no I" interfaces? Just curious -- I use IXXXX for all my interfaces but maybe because I just followed that over from my Java days :)

Primarily because none of our other interfaces use this naming convention, and secondly because that seems to be [what TypeScript recommends in their wiki](https://github.com/Microsoft/TypeScript/wiki/Coding-guidelines#names).

Using `tslint-consistent-codestyle` is going to be too much of a change right now, but it could certainly be a long term goal.

**Comment by sjmcdowall** [comment]
Well to be fair -- those are the "rules" for contributing to TypeScript itself .. but fair enough .. if that's the same rules we want to adopt I'm not a big on it either way ...

**Comment by benjie** [comment]
Yeah; as I say primarily it's due to consistency with our other interfaces 👍

**Comment by cdaringe** [comment]
No sweat from me :)

**Pull request merged**
