### PR TITLE
chore: update to Node 16 LTS in CI & published docker images

### PR DESCRIPTION
**Pull request by Jackbennett**
## Description

The issue is with Node 12 being so old I had TLS connection issues that would hang after startup and silently use all available memory. The node 12 image is using alpine3.15 anyway so this PR keeps alpine the same. While changing versions just moved any reference to node to the current LTS.

## Performance impact

Would expect an improvement.

## Security impact

Published docker images would be using a supported version of Node.
Potentially could remove node 8, 10 and 12 from the matrix as they go out of support.

## Checklist

- [x] My code matches the project's code style and `yarn lint:fix` passes.
- [ ] I've added tests for the new feature, and `yarn test` passes.
- [ ] I have detailed the new feature in the relevant documentation.
- [ ] I have added this feature to 'Pending' in the `RELEASE_NOTES.md` file (if one exists).
- [ ] If this is a breaking change I've explained why.

## Comments

All I've tested is manually installing node 17 within the existing container and things seemed to work fine. Hopefully the CI tests can rundown any issues.

### CODE REVIEW

**Comment by benjie** [comment]
Seems Node 18 and PG 15 are failing across the board, please use Node 16 and limit the scope of this change as much as possible (i.e. don't mess with the Postgres versions). If you'd like to follow up with a PR adding Node 18 support and another PR adding PG15 support to CI those would be great ❤️

**Comment by Jackbennett** [comment]
I did a bit of digging and looks like Webpack 4 -> 5 is required to use node 18, so starting to do that moves quite a lot of package versions. I'm not sure how you want to handle that.

PG15 might be as simple as something in the test init script.  Changed the commits to node 16 only.

**Comment by benjie** [comment]
Let's skip the Node 18 stuff for now; hopefully V5 isn't too far out and that supports Node 18 OOTB already. I think supporting Node 8 -> Node 16 is a wide enough range for V4 😅 

PG15 would be great as a separate PR if you're interested ❤️

**Comment by Jackbennett** [comment]
I'll take a look at pg15.

If you drop node <14 it looks like you can remove whatever the turbo-js stuff is and be faster all the time? Nobody should be using unspoorted node much less as a public api surface.

Tests passed so please let me know if there's anything else you want on this PR, it didn't seem much else of the checklist applied.

**Pull request merged**
