### PR TITLE
chore(deps): bump graphql-ws from 5.1.2 to 5.5.5

### PR DESCRIPTION
**Pull request by enisdenjo**
A few server related improvements have been shipped up until 5.5.5.

Changes worth mentioning:
1. Add support for `ws@v8` ([9119153](https://github.com/enisdenjo/graphql-ws/commit/911915351ea58816db94c8eccfd4226462e2c8b7))
1. Add support for `graphql@v16` ([ad5aea2](https://github.com/enisdenjo/graphql-ws/commit/ad5aea2703d8612a8f5b16814864268fd7f3feb6))
1. use/ws: Handle socket emitted errors ([a22c00f](https://github.com/enisdenjo/graphql-ws/commit/a22c00ff406f19ca706afdf6fdd7de98571bce78))
1. use/ws: Limit server emitted error close message size ([50620df](https://github.com/enisdenjo/graphql-ws/commit/50620dfbe2320cf35724ffc79fda80c836042f25))
1. use/ws: Log server emitted errors to the console ([0826b0a](https://github.com/enisdenjo/graphql-ws/commit/0826b0a994ca79b4589b5feed53d5bc98c88714f))

Also closes #1550

### CODE REVIEW

**Review by benjie — APPROVED** [review]
You missed a release by a few minutes :laughing:

**Comment by enisdenjo** [comment]
I know haha, the release poked me to raise this PR. I thought graphql-ws would've been bumped following https://github.com/graphile/postgraphile/pull/1550#issuecomment-979090301. 🤷‍♂️

**Comment by benjie** [comment]
I don't tend to rush to update minimum dependencies, people can just update their own lockfiles generally :man_shrugging:

**Comment by enisdenjo** [comment]
Completely agree, this PR is mainly due to issues raised with #1550.

**Pull request merged**
