### PR TITLE
Added debug notice

### LINKED ISSUE #607: Print the notice log within postgres stored procedures (plv8 as well) into postgraphql response log
Is it possible to do that? it would be nice for debugging purposes.

Cheers

### PR DESCRIPTION
**Pull request by arshadkazmi42**
Added debug notice in withPostGraphileContext, to print notice logs with Postgres procedures

Closes #607

### CODE REVIEW

**Comment by benjie** [comment]
Looks good! Please run `yarn prettier:fix` to make the code adhere to our standard formatting. I need to take this for a spin before I can merge it, but I don't anticipate having to change anything.

**Comment by arshadkazmi42** [comment]
@benjie Thank you for the review. I will add the formatting and push the code again

**Comment by arshadkazmi42** [comment]
@benjie done with the changes 👍

**Comment by arshadkazmi42** [comment]
@benjie Looks like travis-ci is failing after the formatting changes. Did I do something wrong here?

**Comment by benjie** [comment]
```
src/postgraphile/withPostGraphileContext.ts:349:7 - error TS2552: Cannot find name 'debugNotice'. Did you mean 'debugPgNotice'?
349       debugNotice('NOTICE: %s', msg);
```

^ From Travis. It looks like you've not tested this code locally, that would have shown the same issue. You need to change `debugPgNotice` to `debugNotice`

**Comment by arshadkazmi42** [comment]
@benjie How can I test this locally? Is there any test script written?

**Comment by arshadkazmi42** [comment]
> You need to change `debugPgNotice` to `debugNotice`

You mean, `debugNotice` to `debugPgNotice`
Right?

**Comment by benjie** [comment]
Yeah, you can run `./scripts/dev --` as if it were `postgraphile`; e.g.:

```
./scripts/dev -- -c postgres:///my_db -s app_public --watch
```

**Comment by arshadkazmi42** [comment]
@benjie Is there some docs available to set up the dev environment?

**Comment by benjie** [comment]
Yes, they're in the CONTRIBUTING document: https://github.com/graphile/postgraphile/blob/master/CONTRIBUTING.md

**Comment by arshadkazmi42** [comment]
thank you for verifying. I will try the setup and test it at my end also 👍

**Comment by benjie** [comment]
I've now applied this to errors too, to make errors a lot easier to debug.

```
  postgraphile:postgres:error ERROR[ERR12]: Hi ERROR!! | WHERE: PL/pgSQL function a.e(text) line 1 at RAISE | HINT: Help! +0ms
  postgraphile:postgres:notice NOTICE[ERR12]: Hi NOTICE!! | WHERE: PL/pgSQL function a.n(text) line 1 at RAISE | HINT: Help! +6ms
```

```sql
create or replace function a.e(t text) returns text as $$ begin raise exception 'Hi %', t using errcode = 'ERR12', hint='Help!'; return t; end; $$ language plpgsql stable;
```

```graphql
{
  allPosts {
    nodes {
      nodeId
    }
  }
  e(t:"ERROR!!")
  n(t:"NOTICE!!")
}
```

**Comment by benjie** [comment]
This is great; thanks for having me do these improvements 🤘

**Comment by benjie** [comment]
This is now released: https://github.com/graphile/postgraphile/releases/tag/v4.0.1

**Comment by arshadkazmi42** [comment]
Awesome, Thanks

**Pull request merged**
