### PR TITLE
feat(errors): improve server-side message when JWT expired

### LINKED ISSUE #560: Unhelpful server-side error message when JWT has expired
After working for several days, graphiql now fails to introspect the database. Error reported by postgraphsql is

1 error(s) in 127.12ms :: query IntrospectionQuery { __schema { queryType { name } mutationType { name } types { ...FullType } directives { name description locations args { ...InputValue } } } } fragment FullType on __Type { kind name description fields(includeDeprecated: true) { name description args { ...InputValue } type { ...TypeRef } isDeprecated deprecationReason } inputFields { ...InputValue } interfaces { ...TypeRef } enumValues(includeDeprecated: true) { name description isDeprecated deprecationReason } possibleTypes { ...TypeRef } } fragment InputValue on __InputValue { name description type { ...TypeRef } defaultValue } fragment TypeRef on __Type { kind name ofType { kind name ofType { kind name ofType { kind name ofType { kind name ofType { kind name ofType { kind name ofType { kind name } } } } } } } }

### PR DESCRIPTION
**Pull request by benjie**
screenshot 2018-10-15 17 02 39

Fixes #560

### CODE REVIEW

**Comment by rogerrohrbach** [comment]
👏 Belated thanks for this!

**Comment by benjie** [comment]
YW! How are you getting on with postgraphile@next?

**Comment by rogerrohrbach** [comment]
@benjie Haven't upgraded next, he said, sheepishly.  Just enough budget to get our project into production.  Will upgrade next dev phase.  I'll also lobby the client to make a financial contribution to support your good work.

**Comment by benjie** [comment]
🙏

**Pull request merged**
