### PR TITLE
fix(deps): add missing peer dependencies

### LINKED ISSUE #1250: can't install with yarn berry
```
Error: graphile-utils tried to access graphile-build-pg (a peer dependency) but it isn't provided by its ancestors; this makes the require call ambiguous and unsound.
```

this seems to be related to a peer dependency not declared in the `package.json`

### PR DESCRIPTION
**Pull request by kilianc**
fixes #1250

### CODE REVIEW

**Comment by kilianc** [comment]
adding `graphile-build` and `graphile-build-pg` worked and I made some progress. I am getting this new error now:

```
Error: graphile-build tried to access graphql (a peer dependency) but it isn't provided by its ancestors; this makes the require call ambiguous and unsound.

Required package: graphql (via "graphql")
Required by: graphile-build@virtual:1a3a97e8e942c0e8ed030819493cb029bc52e05804b174630365097cc1befd9bd086eb632b5b1062663a9d7bb9dfe8aa928a5959846ffece67f41a7b8d2191db#npm:4.5.0 (via /opt/app/.yarn/$$virtual/graphile-build-virtual-d6d3af321c/3/.yarn-cache/graphile-build-npm-4.5.0-5c3f17899a-2.zip/node_modules/graphile-build/node8plus/)
```

This is why the `graphql`  change in this PR. No luck so far.

**Comment by kilianc** [comment]
```
➜ yarn
➤ YN0000: ┌ Resolution step
➤ YN0002: │ graphile-build-pg@npm:4.5.3 [0c934] doesn't provide graphql@>=0.9 <0.14 || ^14.0.2 requested by graphile-build@npm:4.5.0
➤ YN0002: │ graphile-build-pg@npm:4.5.3 [0c934] doesn't provide graphql@^0.5.0 || ^0.6.0 || ^0.7.0 || ^0.8.0-b || ^0.9.0 || ^0.10.0 || ^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0 requested by graphql-iso-date@npm:3.6.1
➤ YN0002: │ graphile-build-pg@npm:4.6.0 [adeed] doesn't provide graphql@>=0.9 <0.14 || ^14.0.2 requested by graphile-build@npm:4.6.0
➤ YN0002: │ graphile-build-pg@npm:4.6.0 [adeed] doesn't provide graphql@^0.5.0 || ^0.6.0 || ^0.7.0 || ^0.8.0-b || ^0.9.0 || ^0.10.0 || ^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0 requested by graphql-iso-date@npm:3.6.1
```

**Comment by benjie** [comment]
Hi @kilianc I appreciate you looking into this. I think I'm going to have to dig deeper to figure out exactly what we should be doing. It might be better if everything adds everything else as explicit dependencies in graphile-engine, the risk being that modules will easily come out of sync and install duplicates which is painful - that's why I was using the "loose binding" of peer dependencies currently. We don't want more than one version of _any_ of these modules being installed. Really we want to be able to mark the modules as singletons:

https://twitter.com/leeb/status/1063610033819213824

**Comment by benjie** [comment]
Yarn berry support is being discussed in #1250; it seems it's more complex than this PR. Further, these changes shouldn't be needed since PostGraphile doesn't `require()` `graphile-build` or `graphile-build-pg` directly, so it should not need to list them as dependencies. For these reasons I'm closing this PR.

**Comment by benjie** [comment]
(FWIW, PostGraphile v5 is being built with yarn 2)

**Comment by kilianc** [comment]
@benjie thanks for the update, I completely agree, I just wanted to kick things off. Ready to help!

**Comment by steve-taylor** [comment]
> Further, these changes shouldn't be needed since PostGraphile doesn't `require()` `graphile-build` or `graphile-build-pg` directly, so it should not need to list them as dependencies.

This doesn't quite align with how `peerDependencies` works.

These `peerDependencies` are correctly declared in `graphile-utils` as `graphile-utils` itself directly `require()`s them and doesn't list them in its `dependencies`. This places the onus on any consuming package (`postgraphile` in this case) to either add them as `dependencies` or `peerDependencies`.

That being said, I made all the unmet peer dependencies warnings go away using the following in my project's package.json:

```json
  "dependencies": {
    "graphile-build": "latest",
    "graphile-build-pg": "latest",
    "graphql": "14",
    "pg": "8",
    "postgraphile": "latest"
  }
```

Note that in addition to the two `dependencies` added in this pull request, additional unmet peer dependencies need to be resolved in `graphile-engine`. The above fixes all that in the consuming project's package.json, which is a reasonable workaround.

**Pull request closed without merging**
